### ISSUE TITLE
Show supported Camunda version for properties panel errors

### ISSUE THREAD

**Issue by barmac** [camunda/linting#102]
## What should we do?

Change the properties panel messages to point to Camunda version which supports the feature.

## Why should we do it?

Foster migration. See @nikku's post below:

> Great stuff. Could you create an issue to follow-up on this, consistently applying it across the properties panel? 

> There is other places where we currently validate in the wrong place, and I'd imagine the approach you took could work there, too?

![image](https://github.com/camunda/linting/assets/58601/e48013dd-6e6c-4907-a4da-c60a1ba1c2eb)

_Originally posted by @nikku in https://github.com/camunda/linting/issues/101#issuecomment-1973254746_

**Comment by nikku** [comment]
Adding to `spring cleaning` for now.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/linting/issues/106.
