### ISSUE TITLE
v3.21.0 unknown rule <bpmnlint-plugin-camunda-compat/connector-properties>

### ISSUE THREAD

**Issue by giscafer** [camunda/linting#108]
```js
unknown rule <bpmnlint-plugin-camunda-compat/connector-properties>
    at NestedResolver.resolveRule (webpack://modeler/node_modules/@camunda/linting/lib/Resolver.js:16:0)
    at Linter.resolveRule (webpack://modeler/node_modules/bpmnlint/lib/linter.js:98:0)
    at http://localhost:4100/bundle.js:144003:19
    at Array.map (<anonymous>)
    at http://localhost:4100/bundle.js:143996:34
    at async (webpack://modeler/node_modules/@camunda/linting/lib/Linter.js:82:0)
    at async (webpack://modeler/src/app/App.js:853:20)
    at async http://localhost:4100/bundle.js:76510:14 [ error ]
```
![image](https://github.com/camunda/linting/assets/8676711/b9d60d18-8022-45f7-9004-3a3ee0a70790)

![image](https://github.com/camunda/linting/assets/8676711/83643711-a83a-4a11-b430-206d64042ccb)

![image](https://github.com/camunda/linting/assets/8676711/d95a417d-8e75-4f7b-bbbf-d06eb2a1b8fa)

[NPM@3.21.0](https://www.npmjs.com/package/@camunda/linting?activeTab=code) do not have the code, it is different from the github code

https://github.com/camunda/linting/blob/2935f106a196756c9bab185faea4f0cb8052aea5/lib/compiled-config.js#L96

```js

import rule_3 from 'bpmnlint-plugin-camunda-compat/rules/camunda-cloud/connector-properties';

cache['bpmnlint-plugin-camunda-compat/connector-properties'] = rule_3;
```

suggest to rebuild and publish a new version

**Comment by barmac** [comment]
Thanks for reporting. I can see that the dependency was not updated before the release. This will be fixed in v3.21.1
