### ISSUE TITLE
Warn on duplicate key in custom headers

### ISSUE THREAD

**Issue by pihme** [camunda/linting#4]
In Camunda 8/Zeebe one can define custom headers for
* Service Tasks
* User Tasks
* Send Tasks
* Script Tasks
* Message Intermediate Throw Events

If the custom headers contain entries with duplicate keys, this is an error and will be rejected on deployment.

![image](https://user-images.githubusercontent.com/14032870/175894922-97ff2302-f6b8-4ee3-901c-3f53d703b75c.png)

Related to https://github.com/camunda/zeebe/issues/9416

**Comment by pinussilvestrus** [comment]
@pihme @saig0, for which Zeebe Version should the linting be added? 8.1, 8.0, or even beforehand?

**Comment by pihme** [comment]
Ideally beforehand. Was always an error, we just didn't deal with it in a nice way. 
What is the first version for which you support linting? How do you even differentiate the versions in modeler?

**Comment by pinussilvestrus** [comment]
The engine + version needs to be set via `modeler:executionPlatform` and `modeler:executionPlatformVersion` in the diagram. The linting applies the rules to this version.

The Modeler can configure these properties accordingly, e.g. in the Desktop Modeler

![image](https://user-images.githubusercontent.com/9433996/184602743-1df79ca4-6f0a-452c-935e-8189c1364dbe.png)

I think that's handled similarly in the Web Modeler. @philippfromme please correct me if I'm wrong.
