### ISSUE TITLE
I can attach escalation boundary events on tasks

### ISSUE THREAD

**Issue by saig0** [camunda/linting#46]
## Description

The linting rules for escalation events are not strict enough. In the current Web modeler version for Zeebe `8.2 (alpha)`, I can attach an escalation boundary event to a service or a user task. But Zeebe accepts escalation boundary events only for call activities and subprocesses. 

At the moment, an escalation event can be thrown only by using an escalation throw event. 

If I try to deploy such a process, Zeebe rejects the deployment with a descriptive error message. 

![image](https://user-images.githubusercontent.com/4305769/221871765-b7e3d8f3-3cd5-4794-8bd3-6524cd8e83fd.png)

**Comment by philippfromme** [comment]
I think this requires a new lint rule. It's not about general element support but rather a specific scenario. Thanks for reporting. 👍🏻

**Comment by nikku** [comment]
So this is already integrated in `@camunda/linting`? Or is additional support needed?

**Comment by philippfromme** [comment]
This was fixed by https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/113 which has been integrated. 👍🏻
